// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcAnm9eGktclmFO_W2PRLSMyTae_6LNM4',
    appId: '1:202585338879:web:ff6c87c0a6360bc52e6dca',
    messagingSenderId: '202585338879',
    projectId: 'tcc-serio',
    authDomain: 'tcc-serio.firebaseapp.com',
    storageBucket: 'tcc-serio.firebasestorage.app',
    measurementId: 'G-D7Y8P6PBZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvni6tWnPqygZ4WX5_i0rI4UUzEXbH_Sk',
    appId: '1:202585338879:android:1383af3f79d39a942e6dca',
    messagingSenderId: '202585338879',
    projectId: 'tcc-serio',
    storageBucket: 'tcc-serio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdNB-x3bP_o2XOnLTVZ81-fXaIj-u_78',
    appId: '1:202585338879:ios:2e11c4cd3334c7932e6dca',
    messagingSenderId: '202585338879',
    projectId: 'tcc-serio',
    storageBucket: 'tcc-serio.firebasestorage.app',
    iosBundleId: 'com.example.tccMelhorDeTodos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXdNB-x3bP_o2XOnLTVZ81-fXaIj-u_78',
    appId: '1:202585338879:ios:2e11c4cd3334c7932e6dca',
    messagingSenderId: '202585338879',
    projectId: 'tcc-serio',
    storageBucket: 'tcc-serio.firebasestorage.app',
    iosBundleId: 'com.example.tccMelhorDeTodos',
  );
}
